name: Deploy web version

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deployment:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
        ocaml-compiler:
          - 5.3.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: 0
          filter: tree:0

      # OCaml build
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-pin: false
      - name: Install OCaml dependencies
        run: |
          make deps
      - name: Build
        run: |
          make libjs

      # Node dependencies
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Node.js dependencies
        run: |
          cd webeditor
          npm ci

      # Upload artifact
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: webeditor/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
